### DISCUSSION TITLE
Question about .a file size for iOS.

### DISCUSSION THREAD

**Discussion by howevergoy** [fzyzcjy/flutter_rust_bridge#1257] [Q&A]
I tried to use rust to write SDK for the first time. I noticed that the packaged ios static library is very large, and the final .a file of simple code is 22MB. Is this normal?
![image](https://github.com/fzyzcjy/flutter_rust_bridge/assets/49354784/0099e9ed-ca55-42f5-a983-9001c236acc5)

Later I modified the `Cargo.toml` file.
```toml
[workspace]
members = ["packages/xxim_sdk/native"]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = "symbols"
opt-level = "z"
```

After compilation, the size of the .a file is 6.7M, but it is still large.
![image](https://github.com/fzyzcjy/flutter_rust_bridge/assets/49354784/af2b82a1-ef5d-4955-9b53-8702b8569f34)
Compared with the Android dynamic library, the gap is too big, and the size of the Android dynamic library is only 240KB.
