### DISCUSSION TITLE
Getting Error: Could not parse config from flutter_rust_bridge.yaml: rust_input:  rust_input: invalid type: string "path/src/api.rs", expected a sequence at line 1 column 13

### DISCUSSION THREAD

**Discussion by Vedsaga** [fzyzcjy/flutter_rust_bridge#1717] [Q&A] [answered]
`flutter_rust_bridge.yaml` file

```yaml
rust_input: image_processing/src/api.rs
dart_output: lib/bridge_generated.dart
dart_decl_output: lib/bridge_definitions.dart

```

when run the command below works
```
 flutter_rust_bridge_codegen --rust-input image_processing\src\api.rs --dart-output .\lib\bridge_generated.dart --dart-decl-output .\lib\bridge_definitions.dart
 ```
