### DISCUSSION TITLE
Failed to load dynamic library

### DISCUSSION THREAD

**Discussion by ghost** [fzyzcjy/flutter_rust_bridge#2623] [Q&A]
First `flutter run` then 
`I/flutter ( 4045): Invalid argument(s): Failed to load dynamic library 'libcore.so': dlopen failed: library "libcore.so" not found`

This libcore.so is not packaged into the apk.
The project can run normally on Windows, but Android cannot find the so.

I checked the issues and saw a compile error related to openssl-sys causing the same problem. However, I did not use openssl-sys and did not encounter a compile error. I also encountered this problem.

It's worth mentioning that I used build.gradle.kts

Cargo.toml
```toml
[package]
name = "core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.9.0"

tokio = { version = "1.44.0", features = ["full", "rt-multi-thread"] }
tokio-util = { version = "0.7.13" }
serde = { version = "1.0.219", features = ["derive"] }
anyhow = "*"
futures = "0.3.31"
reqwest = { version = "0.12.12", default-features = false, features = ["rustls-tls", "json", "stream"] }
ring = { version = "0.17.14" }
async-stream = { version = "0.3.6" }
bytes = "*"
zip = "2.2.3"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
```
