### DISCUSSION TITLE
Improve ci/cd

### DISCUSSION THREAD

**Discussion by huang12zheng** [fzyzcjy/flutter_rust_bridge#978] [Ideas]
use
cargo-nextest https://crates.io/crates/cargo-nextest
sccache https://crates.io/crates/sccache( Although, I don't know if it need to be distribution)

I have no experience, but maybe I will try it in the future

**Comment by fzyzcjy** [comment]
Those looks interesting! Feel free to PR :)

**Comment by huang12zheng** [comment]
According to https://github.com/infinyon/fluvio/pull/1229, sccache may not be a good choice.
1. The cicd that needs to be maintained for release
2. cost of install sccache

In addition, I don't know if the following things are useful
```
jobs:
  cancel_previous_runs:
    name: Cancel Previous Runs
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
```
