### ISSUE TITLE
ci: codegen call dart_test_web_integration take too long time

### ISSUE THREAD

**Issue by huang12zheng** [fzyzcjy/flutter_rust_bridge#1174]
1. from
https://github.com/fzyzcjy/flutter_rust_bridge/blob/b45ae48c16d709b194c0ba79354e2c59805f87b2/frb_codegen/src/main.rs

there are two test, please split it in ci.yaml.
2. android run on macos, please run on ubuntu
```yaml
flutter_test_android:
    name: Flutter integration test on Android
    runs-on: macos-latest
    strategy:
      matrix:
        device:
          - "pixel"
          - "Nexus 6"
      fail-fast: false
```
