### ISSUE TITLE
a bug about ci

### ISSUE THREAD

**Issue by huang12zheng** [fzyzcjy/flutter_rust_bridge#1178]
some I know:
* https://github.com/fzyzcjy/flutter_rust_bridge/pull/1054#issuecomment-1505479575

* some pre condition:
```
- id:  rust-toolchain  /// look here
  uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown
          components: rust-src,rustfmt
```
* https://github.com/dtolnay/rust-toolchain

I think "steps.checkout.outputs.rustc_hash"  should be "steps.rust-toolchain.outputs.cachekey"
