### ISSUE TITLE
1.771. ffigen version 

### ISSUE THREAD

**Issue by toplinuxsir** [fzyzcjy/flutter_rust_bridge#1243]
### Describe the bug

cargo build when generate code: 

` value: please update version of ffigen in your dev_dependencies. (version >=8.0.0, <9.0.0)', build.rs:38:5

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
cargo build when generate code: 

` value: please update version of ffigen in your dev_dependencies. (version >=8.0.0, <9.0.0)', build.rs:38:5
```

**Comment by fzyzcjy** [comment]
> please update version of ffigen in your dev_dependencies

So... did you update it?

**Comment by toplinuxsir** [comment]
> > please update version of ffigen in your dev_dependencies
> 
> So... did you update it?

how to update ?   the rust native lib dose not need it /

**Comment by fzyzcjy** [comment]
> in your dev_dependencies

**Comment by fzyzcjy** [comment]
It is a standard dev_dependency IMHO

**Comment by toplinuxsir** [comment]
> dev_dependencies

pubspec.yml 
dev_dependency:
    ffigi:^8.0.2 

Thanks ! I got it .

**Comment by Daanvdplas** [comment]
I have the same error, solved it like toplinuxsir but I have the error:
> SDK version >=3.0.0

I changed it in the `pubspec.yml` but error remains. Can I simply take over the current `pubspec.yml` file from the `frb_example`?

**Comment by Lelant** [comment]
I got the same error, telling me to update ffigen. I updated it in pubspec.yaml. I also needed to update flutter_launcher_icons and change sdk version to ">=3.0.0". Now those packages in my pubspec.yaml are looking like this:

```
environment:
    sdk: ">=3.0.0"

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.2
    ffi: ^2.0.1
    flutter_rust_bridge: ^1.75.1
    meta: ^1.8.0
    permission_handler: ^10.2.0
    stats: ^2.0.0
    path_provider: ^2.0.13
    collection: any
    wakelock: ^0.6.2
    provider: ^6.0.5
    piano: ^1.0.3+1
    json_annotation: ^4.8.0
    camera: ^0.10.4
    path: ^1.8.2
    image_picker: ^0.8.7+3
    flutter_midi: ^1.1.0
    tonic: ^0.2.4
    flutter_svg: ^2.0.5
    intl: ^0.18.1
    uuid: ^3.0.7
    file_picker: ^5.2.10
    wav: ^1.2.0
    audioplayers: ^4.1.0
    json_theme: ^5.0.2+6

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^2.0.0
    ffigen: ^8.0.2
    flutter_native_splash: ^2.2.19
    flutter_launcher_icons: ^0.13.1
    build_runner: ^2.3.3
    json_serializable: ^6.6.1
```

If I add function to the bridge, it builds successfully and I can use them in dart. But I got a syntax error in the native/src/bridge_generated.rs file. The error sais:

```
unresolved import `flutter_rust_bridge::rust2dart::IntoIntoDart`
no `IntoIntoDart` in `rust2dart`
bridge_generated.rs(16, 37): a similar name exists in the module: `IntoDart`
```
The error is in line 16:
```
use flutter_rust_bridge::rust2dart::IntoIntoDart;
```
It is used in line 463 to 481, here is the code:
```
// Section: impl IntoDart

impl support::IntoDart for MediaPlayerState {
    fn into_dart(self) -> support::DartAbi {
        vec![
            self.playing.into_into_dart().into_dart(),
            self.playback_position_factor.into_into_dart().into_dart(),
            self.total_length_seconds.into_into_dart().into_dart(),
            self.looping.into_into_dart().into_dart(),
            self.trim_start_factor.into_into_dart().into_dart(),
            self.trim_end_factor.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for MediaPlayerState {}
impl rust2dart::IntoIntoDart<MediaPlayerState> for MediaPlayerState {
    fn into_into_dart(self) -> Self {
        self
    }
}
```

Is there something wrong with the versions I'm using now?
I'm glad for any help.
