### ISSUE TITLE
[Bug]  V1.81.0 Codegen Error

### ISSUE THREAD

**Issue by The-Mr-L** [fzyzcjy/flutter_rust_bridge#1354]
### Describe the bug

Hi  :) well I just wanted to let you know that for some reason the latest codegen fails but using either 1.79.0 or 1.80.1 seems to work as expected. I have not yet had time to look into it myself. But I will report back if I at some  point know  why :) 

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
2023/09/10 11:46:07 [ERROR] panicked at 'called `Result::unwrap()` on an `Err` value: Error("lex error")', .cargo\registry\src\index.crates.io-6f17d22bba15001f\flutter_rust_bridge_codegen-1.81.0\src\parser\source_graph.rs:359:83
```

**Comment by fzyzcjy** [comment]
Hi, could you please provide a minimal reproducible sample? "lex error" seems like it does not understand something.

**Comment by fzyzcjy** [comment]
Btw, is this related https://github.com/fzyzcjy/flutter_rust_bridge/issues/1328

**Comment by The-Mr-L** [comment]
wellI can understand why you ask for more context since the error seams to be a general one. it was just me thinking you might be able to tell from what has changed since last release. but it is fair.  and btw the latest codegen is running fine in a basic template app on my machine. but in my project it panics. for now I will just stick with 1.80.1. and I will try to make the minimal example hopefully this upcoming week or look into the error myself . thanks again for maintaining this repo!

**Comment by The-Mr-L** [comment]
and I don't think the error is related to the issue mentioned

**Comment by fzyzcjy** [comment]
Hi, it is because "lex error" can mean a lot of things... For example, *which* exact piece of code causes the lex error?

**Comment by The-Mr-L** [comment]
Yes for sure , I understand :)

**Comment by The-Mr-L** [comment]
Okay I am sorry I have not yet had the time to make a test case for this, and since it only seams to be me having the issue I will lose this for now, and report back later if I can't fix it on my end.  with hopefully a more specific error message :)

**Comment by The-Mr-L** [comment]
:)

**Comment by konceptosociala** [comment]
Have the same issue on both 1.81.0 and 1.82.0.

api.rs
```rust
use anyhow::Result;

pub fn my_awesome_function() -> String {
    String::from("Hello, Flutter + Rust!")
}

#[tokio::main(flavor = "current_thread")]
pub async fn my_async_function() -> Result<String> {
    let url = "https://example-files.online-convert.com/document/txt/example.txt";
    let data = reqwest::get(url).await?.text().await?;
    Ok(data)
}
```

Cargo.toml:
```toml
[package]
name = "native"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
anyhow = { version = "1.0.49" }
flutter_rust_bridge = "1.82.0"
futures = "0.3"
reqwest = "0.11.6"
scraper = "0.17.1"
tokio = { version = "1.14.0", features = ["rt", "macros"] }
```

If api.rs is empty, codegen "works"
