### ISSUE TITLE
Method hangs on iOS when another dependency that uses flutter rust bridge exists

### ISSUE THREAD

**Issue by roeierez** [fzyzcjy/flutter_rust_bridge#1712]
### Describe the bug

We use flutter rust bridge in breez: https://github.com/breez.
The plugin is deployed to a different repo: https://github.com/breez/breez-sdk-flutter
When used alone in a flutter mobile app everything works as expected. But when we add bdk_flutter (https://pub.dev/packages/bdk_flutter) which also uses flutter rust bridge, on iOS only, every method hangs.

### Steps to reproduce

1. Create a blank flutter project
2. Add these dependencies:

  ```
breez_sdk:
    git:
      ref: v0.2.15
      url: https://github.com/breez/breez-sdk-flutter.git
  bdk_flutter: ^0.30.0
```
3. Add the following main.dart code:
```
import 'package:flutter/material.dart';
import 'package:breez_sdk/breez_sdk.dart';

void main() async {
  final breezSDK = BreezSDK();
  await breezSDK.mnemonicToSeed("abandon abandon abandon abando");
  runApp(const MyApp());
}
```

The second line in main just hangs.
If we remove the bdk_flutter dependency then it works again.
Happy to provide any information necesary.

### Logs

```shell
Logs:
```

### OS

iOS
