### ISSUE TITLE
Exclude autogenerated files from analyzer

### ISSUE THREAD

**Issue by acul009** [fzyzcjy/flutter_rust_bridge#1961]
### Describe the bug

VSCode was prompting me to run dart fix all the time, but it wanted to fix code from cargokit and the generated code all the time.

I just added the following to my `analysis_options.yaml`:

```yaml
analyzer:
  exclude:
  # Exclude autogenerated files
    - 'rust_builder/**'
    - 'lib/src/rust/**'
```

Is the template project a git repo or is it generated using code?
I'd like to create a pull request to exclude these directories by default if that sounds reasonable to you.

### Steps to reproduce

1) Create Some basic rust code with external structs and enums
2) generate the dart code
3) run `dart fix -n`

### Logs

```shell
---
```

### Version of `flutter_rust_bridge_codegen`

flutter_rust_bridge_codegen 2.0.0-dev.32
