### ISSUE TITLE
Missing pubspec.lock error when attempting generation with pub workspaces enabled

### ISSUE THREAD

**Issue by cabaucom376** [fzyzcjy/flutter_rust_bridge#2281]
### Describe the bug

I just realized that when utilizing the new pub workspaces feature for mono-repos, flutter_rust_bridge fails as there is no longer a pubspec.lock.

### Steps to reproduce

 I have my generated code in a separate "rust" package:
```yaml
# pubspec.yaml

name: # ...
description: # ...
version: 0.1.0
publish_to: 'none'
environment:
  sdk: ">=3.6.0-149.3.beta <4.0.0"

workspace:
  # ...
  - packages/rust

dependencies:
  flutter:
    sdk: flutter
  # ...
  rust:
    path: packages/rust

# ...
```
 ```yaml
# packages/rust/pubspec.yaml

name: rust
version: 1.0.0
publish_to: 'none'
environment:
  sdk: ">=3.6.0-149.3.beta <4.0.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: 2.3.0
  prizm_rust:
    path: ../../rust_builder

dev_dependencies:
  build_runner: ^2.4.12
 ```

### Logs

```shell
Error: missing pubspec.lock in .../app/flutter/packages/rust
```

### Expected behavior

Run generation

### OS

macOS

### Version of `flutter_rust_bridge_codegen`

2.3.0
