### ISSUE TITLE
Github actions fails on `flutter_rust_bridge_codegen generate` step

### ISSUE THREAD

**Issue by VladTheJunior** [fzyzcjy/flutter_rust_bridge#2345]
### Describe the bug

I tried to add github actions for my project, to automatically build release artifacts, but action failed on `- run: flutter_rust_bridge_codegen generate` step.
Can you please help me to properly setup github action to successfully build project

My workflow file:
```yml
name: Windows Release

on:
  push:
    branches: [ "main", "dev" ]


jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Setup flutter_rust_bridge
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: flutter_rust_bridge_codegen
      - run: flutter_rust_bridge_codegen --version
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter --version
      - run: flutter_rust_bridge_codegen generate
      - run: flutter build windows --release
      - uses: actions/upload-artifact@v4
        with:
          name: release
          path: |
            build/windows/x64/runner/Release/
            !build/windows/x64/runner/Release/data/flutter_assets/kernel_blob.bin
```

```shell
flutter_rust_bridge_codegen generate
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
  env:
    CARGO_HOME: C:\Users\runneradmin/.cargo
    CARGO_INCREMENTAL: 0
    CARGO_TERM_COLOR: always
    FLUTTER_ROOT: C:\hostedtoolcache\windows\flutter\stable-3.24.3-x64
    PUB_CACHE: C:\Users\runneradmin\AppData\Local\Pub\Cache
Error: Fail to canonicalize path="D:\\a\\project\\project\\lib/src/rust"

Caused by:
    The system cannot find the path specified. (os error 3)
```
