### ISSUE TITLE
[FRB Codegen] Canonicalization Path Issue OR No such file or directory

### ISSUE THREAD

**Issue by BjarneNiklas** [fzyzcjy/flutter_rust_bridge#2696]
Hey, can someone help us with that?

Info: When the project is finished and ready to use, you will be rewarded. AI cannot help us at the moment. Tried on Windows, Linux and Docker.

### Steps to reproduce

# Problem Description: `flutter_rust_bridge_codegen` Path Canonicalization Error (os error 2) in Docker and Windows

**Tool:** `flutter_rust_bridge_codegen` (tried v2.9.0 and v2.8.0)
**Command:** `flutter_rust_bridge_codegen generate`
**Error:** Consistently fails with `Error: Fail to canonicalize path="..."` followed by `Caused by: No such file or directory (os error 2)`. This occurs when trying to resolve the Dart output path.
**Environment:** The issue occurs both on the Windows 11 host (using PowerShell) and, more persistently, inside a Docker container based on `ubuntu:latest`.

## Docker Environment Details

*   **Base Image:** `ubuntu:latest`
*   **Project Structure:** Code copied via `COPY . /app` in Dockerfile. Project root inside container is `/app`.
*   **CMake:** Initially default Ubuntu version, later updated via direct download/install to **3.29.3**.
*   **Rust/Cargo:** Installed via `rustup`.
*   **Flutter:** v3.22.0 (installed via git clone).
*   **`flutter_rust_bridge_codegen`:** Installed via `cargo install --version <version>`. Tested versions **2.9.0** and **2.8.0**.

## Configuration (`/app/integrations/world_engine/flutter_rust_bridge.yaml`)

The standard configuration uses relative paths:

```yaml
# Configuration for flutter_rust_bridge_codegen

rust_input: "crate::api"

# Path to the root of the Rust crate (directory containing Cargo.toml)
rust_root: "." # Relative to this config file

dart_output: "../world_engine_bindings/lib/bridge_generated.dart" # Relative to this config file
# Provide a single path for C output
# c_output: "../world_engine_bindings/ios/Classes/bridge_generated.h" # Relative to this config file (still commented)
# Optional: Specify class name if needed
# dart_decl_output: "../world_engine_bindings/lib/src/generated/bridge_definitions.dart"
# class_name: "WorldEngine"


[frb_codegen_path_issue.md](https://github.com/user-attachments/files/19822557/frb_codegen_path_issue.md)


### Logs

```shell
Error:** Consistently fails with `Error: Fail to canonicalize path="..."` followed by `Caused by: No such file or directory (os error 2)`. This occurs when trying to resolve the Dart output path.
```

### Generated binding code

```shell

```

### OS

Windows, Linux, Docker

### Version of `flutter_rust_bridge_codegen`

2.9.0

### Flutter info

```shell

```
