### ISSUE TITLE
Code generation issue with missing but needed import and privacy field issue

### ISSUE THREAD

**Issue by dbsxdbsx** [fzyzcjy/flutter_rust_bridge#2780]
### Describe the bug

with the rust side architect like this:
```
rust
├── .gitignore
├── Cargo.lock
├── Cargo.toml
├── src
│   ├── api
│   │   ├── api.rs
│   │   └── mod.rs
│   ├── frb_generated.rs
│   ├── lib.rs
│   └── webdav
│       ├── client.rs
│       ├── mod.rs
│       └── types.rs
└ target....
```
`Cargo.toml` like this:
```toml
[package]
    name   ="rust_lib_test_xxx"
    version="0.1.0"
    edition="2021"

[lib]
    crate-type=["cdylib", "staticlib"]

[profile.release]
    lto          =true
    codegen-units=1
    strip        ="debuginfo"

[profile.dev.package."*"]
    opt-level=3

[dev-dependencies]

[dependencies]
    flutter_rust_bridge="=2.10.0"
    anyhow             ="1"
    thiserror          ="1"
    serde              ={version="1.0", features=["derive"]}
    serde_json         ="1.0"
    bincode            ="1.3.3"

[lints.rust]
    unexpected_cfgs={level="warn", check-cfg=['cfg(frb_expand)']}
```

`flutter_rust_bridge.yaml` liek this:
```yaml
rust_input: crate::api, crate::webdav
dart_output: lib/rust
```
and `rust/src/lib.rs` like this:
```rust
pub mod api;
mod frb_generated;
pub mod webdav;
```
and most importantly, for the module `webdav` of these content:
`webdav/mod.rs`:
```rust
pub mod client;
pub mod types;

pub use client::WebDAVClient;
pub use types::*;
```
`client.rs` :
```rust
use super::types::{WebDAVConfig, WebDAVError, WebDAVResult};

/// 简化的WebDAV客户端，专注于测试WebDAVResult<T>类型
pub struct WebDAVClient {
    config: WebDAVConfig,
}

impl WebDAVClient {
    /// 创建WebDAV客户端
    pub fn new(config: WebDAVConfig) -> Self {
        Self { config }
    }

    /// 测试成功的操作 - 返回WebDAVResult<String>
    pub fn test_success_operation(&self) -> WebDAVResult<String> {
        Ok(format!("成功连接到: {}", self.config.url))
    }

    /// 测试服务器错误的操作 - 返回WebDAVResult<bool>
    pub fn test_server_error_operation(&self) -> WebDAVResult<bool> {
        Err(WebDAVError::ServerError {
            status: 500,
            message: "内部服务器错误".to_string(),
        })
    }
}
```
`types.rs`:
```rust
use thiserror::Error;

/// 简化的WebDAV配置
#[derive(Debug, Clone)]
pub struct WebDAVConfig {
    pub url: String,
    pub username: String,
    pub password: String,
}

/// 简化的WebDAV错误类型
#[derive(Debug, Error)]
pub enum WebDAVError {
    #[error("认证失败")]
    AuthenticationFailed,

    #[error("资源未找到: {0}")]
    ResourceNotFound(String),

    #[error("服务器错误: {status} - {message}")]
    ServerError { status: u16, message: String },

    #[error("配置错误: {0}")]
    ConfigError(String),

    #[error("通用错误: {0}")]
    GenericError(String),
}

/// 自定义WebDAV结果类型 - 这是我们要测试的核心类型
pub type WebDAVResult<T> = Result<T, WebDAVError>;
```

the gened `frb_generated.rs` has issues:
1. the missing import:
```rust
error[E0412]: cannot find type `WebDAVResult` in this scope
   --> src\frb_generated.rs:229:20
    |
229 | impl SseDecode for WebDAVResult<String> {
    |                    ^^^^^^^^^^^^ not found in this scope
    |
help: consider importing this type alias through its public re-export
    |
28  + use crate::webdav::WebDAVResult;
    |
```
2.  `field `config` of `WebDAVClient` is private`, which appears at several places

### Steps to reproduce

1. Gen a baisc frb project, ensure, the 
2. Ensure `rust_input: crate::api, crate::webdav` in `flutter_rust_bridge.yaml`
3. Copy the content for the `Cargo.toml` as stated aboce
4. Add the `webdav` moduel as described above
5. run `flutter_rust_bridge_codegen generate` or `RUST_LOG=debug flutter_rust_bridge_codegen generate`

### Logs

```shell
the full log with `RUST_LOG=debug flutter_rust_bridge_codegen your_args`
https://wani.teracloud.jp/share/11f1d0e906bc6316
```

### Expected behavior

The both 2 issues should not appear after the auto `flutter_rust_bridge_codegen generate`

### Generated binding code

```shell

```

### OS

win10

### Version of `flutter_rust_bridge_codegen`

2.10.0

### Flutter info

```shell
Flutter (Channel stable, 3.32.4,...
```
