### ISSUE TITLE
[Bug] Post release still failing

### ISSUE THREAD

**Issue by Roms1383** [fzyzcjy/flutter_rust_bridge#750]
### Describe the bug

I noticed the post-release workflow job still fails even after my last fix was merged.
Looking at the CI, we can see it fails on `Check no code` job step: it makes a `git diff --exit-code`, but there's some `sed` operations going on beforehand that I don't fully understand, so I don't really know how to fix it yet (I made a few attempts on my fork yesterday, without success).
Looking at the faulty lines, it seems that it's just code that hasn't been linted so it's not much of a big deal, but having the CI fail is always annoying.

```yml
# #467
      - name: "Modify cross-platform code (osx)"
        if: ${{ matrix.os.family == 'osx' }}
        # note the "-i '' -e" is a bug of sed specific to MacOS https://stackoverflow.com/questions/19456518
        run: sed -i '' -e 's/^typedef uintptr_t =.*$/typedef uintptr_t = ffi.UnsignedLong;/g' frb_example/pure_dart/dart/lib/bridge_generated.dart
      - name: "Modify cross-platform code (non-osx)"
        if: ${{ matrix.os.family != 'osx' }}
        run: sed -i -e 's/^typedef uintptr_t =.*$/typedef uintptr_t = ffi.UnsignedLong;/g' frb_example/pure_dart/dart/lib/bridge_generated.dart
```
What is especially confusing to me, is that in `post-release.yml` it is stated that _# NOTE: Please keep in sync with `ci.yaml`_ but at the same time the same steps on `code_generator.yml` (where it was refactored into, from `ci.yml`) are somehow different :

```yml
# #467
      - name: "Modify cross-platform code (windows) (single block)"
        if: ${{ inputs.family == 'windows' }}
        run: sed -i -e 's/^typedef uintptr_t =.*$/typedef uintptr_t = ffi.UnsignedLong;/g' frb_example/pure_dart/dart/lib/bridge_generated.io.dart
```

Maybe that rings a bell ?

That kind of discrepancy could probably be avoided by refactoring the CI to use `just` commands. Basically if the CI runs the same exact commands that we as developers run on our machine, then it's far more unlikely that we'll end up with different results. (I might open a PR for that in the coming weeks, but not yet though, as I have something else I want to work onto first)

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
codegen generated in the CI
```

### OS

Github CI

### Version of `flutter_rust_bridge_codegen`

1.48.0

### Flutter info

```shell
version used in the CI
```

### Version of `clang++`

version used in the CI

### Version of `ffigen`

version used in the CI
