### ISSUE TITLE
Add a "fat" option for codegen

### ISSUE THREAD

**Issue by GregoryConrad** [fzyzcjy/flutter_rust_bridge#947]
# The problem
The issue presented here is still only theoretical with no actual issues caused by it (AFAIK), but I imagine it could present substantial issues in the near future.

At the moment, projects/libraries using FRB need to use the same FRB version amongst Dart and Rust, or else the support libraries might not match up properly. While this makes sense, this can present issues.

Take the following configuration:
```yaml
# A's pubspec.yaml
dependencies:
  b: ^1.0.0
  c: ^1.0.0

# B's pubspec.yaml
dependencies:
  flutter_rust_bridge: "1.58.0"

# C's pubspec.yaml
dependencies:
  flutter_rust_bridge: "1.59.0"
```

Note how the Dart/Rust libraries (B/C) need an exact version of FRB; this is so the support library versions will match up correctly. Otherwise, the project may fail to work correctly, or not even compile.

While using an exact version is the correct fix from the library's perspective, it will create a problem for the end user that relies upon 2+ FRB libraries. Obviously, 1.58.0 and 1.59.0 are not compatible, and Dart will fail to resolve dependencies, or perhaps may force one library to be constrained to an old version (if it can even find one).

Thus, I am proposing a new feature: a "fat" option in FRB itself.

# Proposed solution
Add a new option, I will call it "fat", to codegen that builds "fat" Dart files. These "fat" Dart files bundle the necessary FRB support code alongside the generated FFI interop code in the same Dart files. This would remove the Dart FRB package dependency, fixing the problem altogether. In the future, once/if this solution is implemented, it also might be a good idea to discontinue the Dart package altogether and simply force the use of this "fat" option.
